spring:
  datasource:
    click:
      driver-class-name: com.clickhouse.jdbc.ClickHouseDriver
      jdbc-url: jdbc:clickhouse://10.4.10.3:8123/yzl_dw
      password: Default@123
      username: default
      initialSize: 10
      maxActive: 10
      maxWait: 6000
      validationQuery: select 1
    mysql:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://127.0.0.1/test?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
      password: root_pwd
      username: root
      initialSize: 20
      maxActive: 50
      maxWait: 2000
      validationQuery: select 1